from __future__ import annotations

from typing import Any, Dict, List


RULE_REGISTRY: Dict[str, Dict[str, Any]] = {
    "simileDensity": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style"],
    },
    "hedgeAdverbs": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style"],
    },
    "tellingEmotion": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style"],
    },
    "formulaicTransition": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style"],
    },
    "contrastFlipPattern": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "ai-phrasing"],
    },
    "analogicalPivotPattern": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "ai-phrasing"],
    },
    "templateCatchphrasePattern": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "ai-phrasing", "dialogue"],
    },
    "sensoryVariety": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "low",
        "tags": ["style"],
    },
    "paragraphReadability": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "readability", "mobile-reading"],
    },
    "paragraphUniformity": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "low",
        "tags": ["style"],
    },
    "sentenceRepetition": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "low",
        "tags": ["style"],
    },
    "specialTermRepetition": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "term-policy"],
    },
    "registerDrift": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "register-policy"],
    },
    "narrativeFrameRepetition": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "frame-policy"],
    },
    "structuredPlanBlock": {
        "source": "core",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "plan-block"],
    },
    "metaLeakage": {
        "source": "review-rule-profile",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "review-rules", "meta-leakage"],
    },
    "povOverreach": {
        "source": "review-rule-profile",
        "scope": "chapter",
        "kind": "style",
        "severity": "medium",
        "tags": ["style", "review-rules", "pov"],
    },
    "stateContradiction": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "error",
        "tags": ["consistency"],
    },
    "relationContradiction": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "error",
        "tags": ["consistency"],
    },
    "timelineConflict": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "error",
        "tags": ["consistency"],
    },
    "outlineDeviation": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["consistency", "outline"],
    },
    "settingConflict": {
        "source": "core",
        "scope": "world",
        "kind": "hard",
        "severity": "warning",
        "tags": ["consistency", "worldbook"],
    },
    "unintroducedNameReveal": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["consistency", "cognitive-boundary"],
    },
    "capabilityTaskMismatch": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["consistency", "entity-state", "plausibility"],
    },
    "powerProgressionConflict": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["consistency", "worldbook", "progression"],
    },
    "wrappedEntityMissingRegistry": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "warning",
        "tags": ["review", "registry-coverage"],
    },
    "chapterHandoffWeak": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["review", "continuity", "chapter-handoff"],
    },
    "missing-file": {
        "source": "core",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "project-shape"],
    },
    "invalid-json-compatible-yaml": {
        "source": "core",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "project-shape"],
    },
    "invalid-illustrations": {
        "source": "core",
        "scope": "export",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "illustration"],
    },
    "wrapped-entity-coverage": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "registry-coverage", "wrapped-entity"],
    },
    "wrapped-entity-missing-registry": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "registry-coverage", "wrapped-entity"],
    },
    "known-reference-unwrapped": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "registry-coverage", "plain-mention"],
    },
    "unclosed-wrapped-entity-tag": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "wrapped-entity", "tag-syntax"],
    },
    "empty-wrapped-entity-tag": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "wrapped-entity", "tag-syntax"],
    },
    "invalid-wrapped-entity-tag": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "wrapped-entity", "tag-syntax"],
    },
    "illustration-target-missing": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-target-not-found": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-target-chapter-file-missing": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-input-missing": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-input-not-found": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-mask-not-found": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-missing-assets": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-asset-count-mismatch": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-primary-asset-invalid": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-primary-path-mismatch": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-asset-path-missing": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-asset-outside-root": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "missing-illustration-asset": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "illustration-asset-bytes-mismatch": {
        "source": "core",
        "scope": "export",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "illustration"],
    },
    "orphan-illustration-asset": {
        "source": "core",
        "scope": "export",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "illustration"],
    },
    "parsed-file": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "project-shape"],
    },
    "missing-primary-genre": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate"],
    },
    "missing-target-audience": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate"],
    },
    "missing-core-promises": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate"],
    },
    "missing-pace-contract": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate"],
    },
    "non-normalized-primary-genre": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate", "normalization"],
    },
    "genre-primary-mismatch": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-gate", "normalization"],
    },
    "non-normalized-story-template-id": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template", "normalization"],
    },
    "invalid-story-template-module-policy": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "invalid-story-template-module-mode": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-required-worldbook": {
        "source": "project-pack",
        "scope": "world",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-required-world-rules": {
        "source": "project-pack",
        "scope": "world",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-required-factions": {
        "source": "project-pack",
        "scope": "world",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-required-foreshadow-ledger": {
        "source": "project-pack",
        "scope": "world",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "empty-required-foreshadow-ledger": {
        "source": "project-pack",
        "scope": "world",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-character-state-tracking": {
        "source": "project-pack",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "story-template"],
    },
    "missing-commercial-premise": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-hook-line": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-hook-stack": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-target-platform": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-serialization-model": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-benchmarks": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-commercial-release-cadence": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "commercial-positioning"],
    },
    "commercial-word-target-order": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "commercial-positioning"],
    },
    "missing-style-profiles": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-profiles": {
        "source": "project-pack",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-profiles-shape": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "missing-active-style-profile": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-profile-payload": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-thresholds": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-threshold-value": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-extra-patterns": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-style-pattern-list": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "style-profile"],
    },
    "active-style-profile": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "style-profile"],
    },
    "parsed-style-profiles": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "style-profile"],
    },
    "invalid-review-rules": {
        "source": "project-pack",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "review-rules"],
    },
    "missing-review-rule-profiles": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "invalid-review-rules-shape": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "missing-active-review-rule-profile": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "invalid-review-rule-profile-payload": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "invalid-review-rule-enabled-rules": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "invalid-review-rule-exemptions": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "invalid-review-rule-exemption": {
        "source": "project-pack",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "review-rules"],
    },
    "active-review-rule-profile": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "review-rules"],
    },
    "parsed-review-rules": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "review-rules"],
    },
    "style-profile-override": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "style-profile"],
    },
    "style-profile-custom": {
        "source": "project-pack",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "style-profile"],
    },
    "missing-chapter-id": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "workflow", "chapter-structure"],
    },
    "missing-chapter-file": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "workflow", "chapter-structure"],
    },
    "orphan-chapter-file": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "chapter-structure"],
    },
    "missing-active-chapter": {
        "source": "core",
        "scope": "chapter",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "chapter-structure"],
    },
    "active-chapter-not-in-outline": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "chapter-structure"],
    },
    "missing-context-chapter": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "chapter-structure"],
    },
    "chapter-file": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "chapter-structure"],
    },
    "active-chapter": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "chapter-structure"],
    },
    "context-chapter": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "chapter-structure"],
    },
    "missing-root-file": {
        "source": "core",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "project-shape"],
    },
    "missing-workflow-dir": {
        "source": "core",
        "scope": "project",
        "kind": "hard",
        "severity": "error",
        "tags": ["doctor", "project-shape"],
    },
    "root-file": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "project-shape"],
    },
    "workflow-dir": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "project-shape"],
    },
    "missing-project-prd": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-brief", "prd"],
    },
    "project-prd-incomplete": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "project-brief", "prd"],
    },
    "missing-outline-volumes": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "outline-structure"],
    },
    "completed-chapter-has-planned-beat": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "outline-structure"],
    },
    "entity-missing-profile": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "entity-profile"],
    },
    "entity-missing-seed": {
        "source": "core",
        "scope": "entity",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "entity-profile"],
    },
    "inferred-entity-missing-profile": {
        "source": "core",
        "scope": "entity",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "entity-profile"],
    },
    "thread-unresolved": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "thread-health"],
    },
    "thread-density": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "thread-health"],
    },
    "thread-overdue-count": {
        "source": "core",
        "scope": "project",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "thread-health"],
    },
    "thread-open-count": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "thread-health"],
    },
    "arc-missing_motivation": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "arc-health"],
    },
    "arc-no_milestones": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "arc-health"],
    },
    "arc-invalid_chapter": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "arc-health"],
    },
    "arc-fracture_risk": {
        "source": "core",
        "scope": "entity",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "arc-health"],
    },
    "arc-missing-definition": {
        "source": "core",
        "scope": "entity",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "arc-health"],
    },
    "structure-missing_critical_beat": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "structure-health"],
    },
    "structure-adjacent_same_chapter": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "structure-health"],
    },
    "structure-unmapped_beat": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "structure-health"],
    },
    "structure-coverage": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "structure-health"],
    },
    "chapter-outline-not-ready": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "outline-structure"],
    },
    "chapter-below-minimum": {
        "source": "core",
        "scope": "chapter",
        "kind": "soft",
        "severity": "warning",
        "tags": ["doctor", "chapter-word-count"],
    },
    "chapter-below-target": {
        "source": "core",
        "scope": "chapter",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "chapter-word-count"],
    },
    "missing-core-emotions": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "project-gate"],
    },
    "missing-chapter-emotion-floor": {
        "source": "core",
        "scope": "project",
        "kind": "info",
        "severity": "info",
        "tags": ["doctor", "project-gate"],
    },
    "missing-outline-direction": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "outline-gate"],
    },
    "missing-direction": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "outline-gate"],
    },
    "missing-chapter-entry": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "outline-gate"],
    },
    "missing-beats": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "outline-gate"],
    },
    "missing-scene-plans": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "outline-gate"],
    },
    "missing-chapter-review": {
        "source": "core",
        "scope": "chapter",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "review-gate"],
    },
    "missing-scene-review": {
        "source": "core",
        "scope": "scene",
        "kind": "gate",
        "severity": "warning",
        "tags": ["workflow", "review-gate"],
    },
}


def _copy_rule_definition(definition: Dict[str, Any]) -> Dict[str, Any]:
    copied = dict(definition)
    copied["tags"] = list(definition.get("tags", []))
    return copied


def _merge_rule_tags(default_tags: List[str], extra_tags: List[str] | None) -> List[str]:
    merged: List[str] = []
    for tag in list(default_tags) + list(extra_tags or []):
        text = str(tag).strip()
        if text and text not in merged:
            merged.append(text)
    return merged


def get_rule_definition(rule_id: str) -> Dict[str, Any]:
    definition = RULE_REGISTRY.get(rule_id, {})
    if definition:
        return _copy_rule_definition(definition)
    if rule_id.startswith("project-"):
        base_definition = RULE_REGISTRY.get(rule_id[len("project-") :], {})
        if base_definition:
            copied = _copy_rule_definition(base_definition)
            tags = list(copied.get("tags", []))
            if "project-gate" not in tags:
                tags.append("project-gate")
            copied["tags"] = tags
            return copied
    return {}


def resolve_rule_metadata(
    rule_id: str,
    *,
    source: str | None = None,
    scope: str | None = None,
    kind: str | None = None,
    severity: str | None = None,
    tags: List[str] | None = None,
) -> Dict[str, Any]:
    definition = get_rule_definition(rule_id)
    resolved = {
        "source": source or str(definition.get("source", "")),
        "scope": scope or str(definition.get("scope", "")),
        "kind": kind or str(definition.get("kind", "")),
        "severity": severity or str(definition.get("severity", "")),
        "tags": _merge_rule_tags(list(definition.get("tags", [])), tags),
    }
    missing = [key for key in ("source", "scope", "kind", "severity") if not resolved[key]]
    if missing:
        raise ValueError(f"rule metadata incomplete for {rule_id}: missing {', '.join(missing)}")
    return resolved
