#!/usr/bin/env sh

set -eu

if [ $# -lt 1 ]; then
    echo "Usage: $0 <git-range>" >&2
    exit 1
fi

RANGE="$1"
HAS_ERROR=0

for COMMIT in $(git rev-list "$RANGE"); do
    MSG=$(git log -1 --format="%B" "$COMMIT")
    FIRST_LINE=$(echo "$MSG" | head -1)

    if echo "$FIRST_LINE" | grep -qE "^Merge "; then
        continue
    fi

    if echo "$MSG" | grep -qiE "^Co-Authored-By:|^Co-authored-by:|^Pair-Programmed-By:|Generated by|Generated with"; then
        echo "ERROR: Forbidden trailer in commit $(git log -1 --format='%h' "$COMMIT")" >&2
        HAS_ERROR=1
    fi

    VALID_TYPES="feat|fix|docs|refactor|test|chore|build|ci|perf|revert|style"
    if ! echo "$FIRST_LINE" | grep -qE "^(${VALID_TYPES})(\\([^)]+\\))?: .+"; then
        echo "ERROR: Non-conventional commit $(git log -1 --format='%h %s' "$COMMIT")" >&2
        HAS_ERROR=1
    fi
done

exit $HAS_ERROR
