#!/usr/bin/env sh

set -eu

if [ $# -lt 1 ]; then
    echo "Usage: $0 <commit-message-file>" >&2
    exit 1
fi

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")

if echo "$MSG" | grep -qiE "^Co-Authored-By:|^Co-authored-by:|^Pair-Programmed-By:|Generated by|Generated with"; then
    echo "ERROR: Forbidden trailer or AI signature detected in commit message." >&2
    exit 1
fi

FIRST_LINE=$(echo "$MSG" | head -1)
VALID_TYPES="feat|fix|docs|refactor|test|chore|build|ci|perf|revert|style"

if ! echo "$FIRST_LINE" | grep -qE "^(${VALID_TYPES})(\\([^)]+\\))?: .+"; then
    echo "ERROR: Commit message does not follow Conventional Commits format." >&2
    echo "Expected: <type>(<scope>): <description>" >&2
    exit 1
fi
